version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teste_backend
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    networks:
      - teste_network
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=teste_bd
      - DB_USERNAME=root
      - DB_PASSWORD=root

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: teste_bd
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - teste_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - teste_network

networks:
  teste_network:

volumes:
  mysql_data:
