version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teste_backend
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=teste_bd
      - DB_USERNAME=root
      - DB_PASSWORD=root
    command: bash -c "sleep 10 && php artisan migrate && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste_bd
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
